### ISSUE TITLE
Write up decisions on changes to JavaScript API

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system-architecture#30]
## What

Write up a decision record that covers the changes we're making to the JavaScript API for the components in GOV.UK Frontend.

The decision record should live in the [architecture repo](https://github.com/alphagov/govuk-design-system-architecture/) and follow the same format as [the provided template](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/000-template.md).

## Why

Writing up these decisions gives us a place to record the rationale, which will help our future selves when we want to understand why things are the way they are.

It will also ensure we're all on the same page in the short term, and aid us when reviewing code changes.

Finally, we can use it to communicate the upcoming changes to the rest of the team and to our users.

## Who needs to work on this

Developers

## Who needs to review this

Developers, Tech Writer?

## Done when

- [x] Decision record written up
- [ ] Decision record reviewed and merged

**Comment by romaricpascal** [comment]
Closing as this has been handled by the following PRs:
- https://github.com/alphagov/govuk-design-system-architecture/pull/31
- https://github.com/alphagov/govuk-design-system-architecture/pull/32
- https://github.com/alphagov/govuk-design-system-architecture/pull/33
